temporarily use forked repo for openshift config.

diff --git a/frontend/openshift/templates/nginx-runtime/s2i/bin/run b/frontend/openshift/templates/nginx-runtime/s2i/bin/run
--- a/frontend/openshift/templates/nginx-runtime/s2i/bin/run
+++ b/frontend/openshift/templates/nginx-runtime/s2i/bin/run
@@ -1,67 +1,8 @@
 #!/bin/bash
 
-getApiProxyConfigSection (){
-# ================================================================================
-# Generate the /api proxy configuration section.
-#
-# Assumes there is a default for API_URL
-# --------------------------------------------------------------------------------
-# API_URL:
-#  - The URL for the API endpoint.
-# ================================================================================
-proxyUrl=${1%/}
-
-read -r -d '' _FORWARDED_HEADERS << EOF
-
-            proxy_set_header Host               \$host;
-            proxy_set_header X-Real-IP          \$remote_addr;
-            proxy_set_header X-Forwarded-For    \$proxy_add_x_forwarded_for;
-            proxy_set_header X-Forwarded-Host   \$host;
-            proxy_set_header X-Forwarded-Server \$host;
-            proxy_set_header X-Forwarded-Port   \$proxy_port;
-            proxy_set_header X-Forwarded-Proto  \$proxy_scheme;
-
-EOF
-
-read -r -d '' _CONFIG_SECTION << EOF
-        # proxy requests to the API
-        location /api/indy/ {
-            proxy_pass ${proxyUrl}/indy/;
-        }
-        location /api/static/ {
-            ${_FORWARDED_HEADERS}
-            proxy_pass ${proxyUrl%/v2}/static/;
-        }
-        location /api {
-            limit_except OPTIONS {
-                ${HTTP_BASIC}
-            }
-            proxy_set_header Authorization "";
-            ${_FORWARDED_HEADERS}
-            proxy_pass ${proxyUrl};
-        }
-        location /api/v2 {
-            limit_except OPTIONS {
-                ${HTTP_BASIC}
-            }
-            proxy_set_header Authorization "";
-            ${_FORWARDED_HEADERS}
-            proxy_pass ${proxyUrl};
-        }
-        location = /api/v2 {
-            # allow access to swagger
-            proxy_set_header Authorization "";
-            ${_FORWARDED_HEADERS}
-            proxy_pass ${proxyUrl};
-        }
-EOF
-
-echo "${_CONFIG_SECTION}"
-}
-
 getApiUrl (){
   # ================================================================================
-  # Extract the API URL from the container's environment variables based on
+  # Extract the API URL from the container's environment variables based on 
   # OpenShift service conventions.
   # --------------------------------------------------------------------------------
   # API_URL:
@@ -75,39 +16,39 @@ getApiUrl (){
   #
   # API_PATH:
   #  - The root path for the API.
-  #  - For example /api/v2/
+  #  - For example /api/v1/
   # --------------------------------------------------------------------------------
   # Examples:
-  #
+  # 
   # 1)
-  #   API_URL=https://dev-demo-api.orgbook.gov.bc.ca/api/v2/
+  #   API_URL=https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1/   
   #   API_SERVICE_NAME=django
-  #   DJANGO_SERVICE_HOST=172.50.105.217
-  #   DJANGO_SERVICE_PORT=8080
-  #   API_PATH=/api/v2/
+  #   DJANGO_SERVICE_HOST=172.50.105.217                                                                                                                                                                                        
+  #   DJANGO_SERVICE_PORT=8080                                                                                                                                                                                                  
+  #   API_PATH=/api/v1/
   #
-  #   Results in API_URL=http://172.50.105.217:8080/api/v2/
-  #
+  #   Results in API_URL=http://172.50.105.217:8080/api/v1/
+  # 
   # 2)
-  #   API_URL=https://dev-demo-api.orgbook.gov.bc.ca/api/v2/
+  #   API_URL=https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1/   
   #   API_SERVICE_NAME=django
-  #   DJANGO_SERVICE_HOST=172.50.105.217
-  #   API_PATH=/api/v2/
+  #   DJANGO_SERVICE_HOST=172.50.105.217                                                                                                                                                                                        
+  #   API_PATH=/api/v1/
   #
-  #   Results in API_URL=http://172.50.105.217/api/v2/
+  #   Results in API_URL=http://172.50.105.217/api/v1/
   #
   # 3)
   #   If either API_SERVICE_NAME or *_SERVICE_HOST are not defined...
+  # 
+  #   API_URL=https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1/   
   #
-  #   API_URL=https://dev-demo-api.orgbook.gov.bc.ca/api/v2/
-  #
-  #   Results in API_URL=https://dev-demo-api.orgbook.gov.bc.ca/api/v2/
+  #   Results in API_URL=https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1/   
   # ================================================================================
+  echo ${API_SERVICE_NAME}
   if [ ! -z "${API_SERVICE_NAME}" ]; then
     _SERVICE_NAME="$(tr '[:lower:]' '[:upper:]' <<< ${API_SERVICE_NAME/-/_})"
     _SERVICE_HOST_NAME=${_SERVICE_NAME}_SERVICE_HOST
     _SERVICE_PORT_NAME=${_SERVICE_NAME}_SERVICE_PORT
-
     if [ ! -z "${!_SERVICE_HOST_NAME}" ]; then
       if [ ! -z "${!_SERVICE_PORT_NAME}" ]; then
         API_URL="http://${!_SERVICE_HOST_NAME}:${!_SERVICE_PORT_NAME}${API_PATH}"
@@ -116,71 +57,23 @@ getApiUrl (){
       fi
     fi
   fi
-
+  
   echo ${API_URL}
 }
 
-getRemoveBaseHref() {
-  # If we are nested under a subpath, remove the subpath before processing URLs
-  # Base href must have a leading and trailing slash
-  BASE="$1"
-  if [ ! -z "${BASE}" ] && [ "${BASE}" != "/" ]; then
-    echo "rewrite ^${BASE}(.*)\$ /\$1 last;"
-  fi
-}
-
-if [ -n "$HTTP_BASIC_USERNAME" ] && [ -n "$HTTP_BASIC_PASSWORD" ]; then
-    echo "---> Generating .htpasswd file"
-    `echo "$HTTP_BASIC_USERNAME:$(openssl passwd -crypt $HTTP_BASIC_PASSWORD)" > /tmp/.htpasswd`
-    if [ -z "${HTTP_BASIC+test}" ] || [ "on" == "${HTTP_BASIC}" ] || [ "1" == "${HTTP_BASIC}" ]; then
-      HTTP_BASIC="auth_basic 'restricted';"
-    elif [ "0" == "${HTTP_BASIC}" ] || [ "off" == "${HTTP_BASIC}" ]; then
-      HTTP_BASIC=""
-    fi
+API_URL=$(getApiUrl)
+echo ${API_URL}
+if [ -z "$API_URL" ]; then
+  echo "Could not find API Service to proxy to, exiting"
+  exit 1
 fi
-
-export RealIpFrom="${RealIpFrom:-172.51.0.0/16}"
-export TOB_THEME="${TOB_THEME:-}"
-export WEB_BASE_HREF="${WEB_BASE_HREF:-/}"
-export REMOVE_BASE_HREF=$(getRemoveBaseHref ${WEB_BASE_HREF})
-export API_URL=$(getApiUrl)
-if [ ! -z "${API_URL}" ]; then
-	# ================================================================================
-	# If an API_URL is defined, generate an /api proxy configuration section and
-	# escape it so sed can digest it and process it properly.
-	# Otherwise leave things undefined so the placeholder in the template gets
-	# replaced with a blank string.
-	# ================================================================================
-	API_CONFIG_SECTION=$(getApiProxyConfigSection "${API_URL}")
-	API_CONFIG_SECTION="$(echo "${API_CONFIG_SECTION}" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/\$/\\$/g')"
-fi
-
-makeReplacementPattern() {
-  # Generate a replacement pattern for sed in order to replace our variables in
-  # the nginx configuration template
-  REPLACE=""
-  for VAR in $@; do
-    REPLACE+="s~%${VAR}%~${!VAR}~g; "
-  done
-  echo "${REPLACE}"
-}
 
 echo "---> Replacing Configuration ..."
 echo "Setting:"
-echo "RealIpFrom = ${RealIpFrom}"
-echo "IpFilterRules = ${IpFilterRules}"
-echo "AdditionalRealIpFromRules = ${AdditionalRealIpFromRules}"
+echo "RealIpFrom = ${RealIpFrom:-172.51.0.0/16}"
+API_URL="http://localhost:5000"
 echo "API_URL = ${API_URL}"
-echo "HTTP_BASIC = ${HTTP_BASIC}"
-echo "TOB_THEME = ${TOB_THEME}"
-echo "WEB_BASE_HREF = ${WEB_BASE_HREF}"
 
-REPLACE_VARS="
-  RealIpFrom IpFilterRules AdditionalRealIpFromRules
-  HTTP_BASIC TOB_THEME WEB_BASE_HREF REMOVE_BASE_HREF API_CONFIG_SECTION
-"
-
-sed "$(makeReplacementPattern $REPLACE_VARS)" /tmp/nginx.conf.template > /etc/nginx/nginx.conf
-
+sed "s~%RealIpFrom%~${RealIpFrom:-172.51.0.0/16}~g; s~%API_URL%~${API_URL}~g;" /tmp/nginx.conf.template > /etc/nginx/nginx.conf
 echo "---> Starting nginx ..."
 /usr/sbin/nginx -g "daemon off;"
